import { Vehicle, Mechanic, BreakdownReport, NotificationAlert, FAQItem } from './types';

export const CHENNAI_LOCATIONS = [
  'Chennai',
  'Tambaram',
  'Pallavaram',
  'Velachery',
  'Guindy',
  'Porur',
  'Ambattur',
  'Avadi',
  'Anna Nagar',
  'T Nagar',
  'Sholinganallur',
  'Chengalpattu',
  'Sriperumbudur',
];

// Vehicle data – 100 entries (first 45 from user list, rest placeholders)
export const INITIAL_VEHICLES: Vehicle[] = [
  // 1-45 user-provided
  { id: 'veh-1', plate: 'TN 01 AB 0001', brand: 'Toyota', model: 'Camry', year: 2021, color: 'White', status: 'ready', type: 'Car' },
  { id: 'veh-2', plate: 'TN 01 AB 0002', brand: 'Honda', model: 'Civic', year: 2022, color: 'Black', status: 'ready', type: 'Car' },
  { id: 'veh-3', plate: 'TN 01 AB 0003', brand: 'Hyundai', model: 'Creta', year: 2023, color: 'Silver', status: 'ready', type: 'Car' },
  { id: 'veh-4', plate: 'TN 01 AB 0004', brand: 'Maruti Suzuki', model: 'Swift', year: 2024, color: 'Red', status: 'ready', type: 'Car' },
  { id: 'veh-5', plate: 'TN 01 AB 0005', brand: 'Kia', model: 'Seltos', year: 2025, color: 'Blue', status: 'ready', type: 'Car' },
  { id: 'veh-6', plate: 'TN 01 AB 0006', brand: 'Tata', model: 'Nexon', year: 2021, color: 'Grey', status: 'ready', type: 'Car' },
  { id: 'veh-7', plate: 'TN 01 AB 0007', brand: 'Mahindra', model: 'XUV700', year: 2022, color: 'Black', status: 'ready', type: 'Car' },
  { id: 'veh-8', plate: 'TN 01 AB 0008', brand: 'Toyota', model: 'Fortuner', year: 2023, color: 'White', status: 'ready', type: 'Car' },
  { id: 'veh-9', plate: 'TN 01 AB 0009', brand: 'Honda', model: 'City', year: 2024, color: 'Brown', status: 'ready', type: 'Car' },
  { id: 'veh-10', plate: 'TN 01 AB 0010', brand: 'Hyundai', model: 'Verna', year: 2025, color: 'Blue', status: 'ready', type: 'Car' },
  { id: 'veh-11', plate: 'TN 01 AB 0011', brand: 'Maruti Suzuki', model: 'Baleno', year: 2021, color: 'Silver', status: 'ready', type: 'Car' },
  { id: 'veh-12', plate: 'TN 01 AB 0012', brand: 'Kia', model: 'Sonet', year: 2022, color: 'Red', status: 'ready', type: 'Car' },
  { id: 'veh-13', plate: 'TN 01 AB 0013', brand: 'Tata', model: 'Punch', year: 2023, color: 'Orange', status: 'ready', type: 'Car' },
  { id: 'veh-14', plate: 'TN 01 AB 0014', brand: 'Mahindra', model: 'Scorpio-N', year: 2024, color: 'Green', status: 'ready', type: 'Car' },
  { id: 'veh-15', plate: 'TN 01 AB 0015', brand: 'Toyota', model: 'Innova Hycross', year: 2025, color: 'White', status: 'ready', type: 'Car' },
  { id: 'veh-16', plate: 'TN 01 AB 0016', brand: 'Hyundai', model: 'i20', year: 2021, color: 'Yellow', status: 'ready', type: 'Car' },
  { id: 'veh-17', plate: 'TN 01 AB 0017', brand: 'Honda', model: 'Amaze', year: 2022, color: 'Grey', status: 'ready', type: 'Car' },
  { id: 'veh-18', plate: 'TN 01 AB 0018', brand: 'Maruti Suzuki', model: 'Brezza', year: 2023, color: 'Blue', status: 'ready', type: 'Car' },
  { id: 'veh-19', plate: 'TN 01 AB 0019', brand: 'Tata', model: 'Harrier', year: 2024, color: 'Black', status: 'ready', type: 'Car' },
  { id: 'veh-20', plate: 'TN 01 AB 0020', brand: 'Kia', model: 'Carens', year: 2025, color: 'Silver', status: 'ready', type: 'Car' },
  { id: 'veh-21', plate: 'TN 01 AB 0021', brand: 'Nissan', model: 'Magnite', year: 2023, color: 'Red', status: 'ready', type: 'Car' },
  { id: 'veh-22', plate: 'TN 01 AB 0022', brand: 'Renault', model: 'Kiger', year: 2022, color: 'Orange', status: 'ready', type: 'Car' },
  { id: 'veh-23', plate: 'TN 01 AB 0023', brand: 'Volkswagen', model: 'Virtus', year: 2024, color: 'White', status: 'ready', type: 'Car' },
  { id: 'veh-24', plate: 'TN 01 AB 0024', brand: 'Skoda', model: 'Slavia', year: 2025, color: 'Blue', status: 'ready', type: 'Car' },
  { id: 'veh-25', plate: 'TN 01 AB 0025', brand: 'MG', model: 'Hector', year: 2021, color: 'Black', status: 'ready', type: 'Car' },
  { id: 'veh-26', plate: 'TN 01 AB 0026', brand: 'Jeep', model: 'Compass', year: 2022, color: 'Green', status: 'ready', type: 'Car' },
  { id: 'veh-27', plate: 'TN 01 AB 0027', brand: 'Toyota', model: 'Glanza', year: 2023, color: 'Silver', status: 'ready', type: 'Car' },
  { id: 'veh-28', plate: 'TN 01 AB 0028', brand: 'Hyundai', model: 'Venue', year: 2024, color: 'White', status: 'ready', type: 'Car' },
  { id: 'veh-29', plate: 'TN 01 AB 0029', brand: 'Honda', model: 'Elevate', year: 2025, color: 'Brown', status: 'ready', type: 'Car' },
  { id: 'veh-30', plate: 'TN 01 AB 0030', brand: 'Kia', model: 'EV6', year: 2021, color: 'Grey', status: 'ready', type: 'Car' },
  { id: 'veh-31', plate: 'TN 01 AB 0031', brand: 'Tata', model: 'Tiago', year: 2022, color: 'Yellow', status: 'ready', type: 'Car' },
  { id: 'veh-32', plate: 'TN 01 AB 0032', brand: 'Mahindra', model: 'Thar', year: 2023, color: 'Red', status: 'ready', type: 'Car' },
  { id: 'veh-33', plate: 'TN 01 AB 0033', brand: 'Maruti Suzuki', model: 'Fronx', year: 2024, color: 'Blue', status: 'ready', type: 'Car' },
  { id: 'veh-34', plate: 'TN 01 AB 0034', brand: 'Toyota', model: 'Urban Cruiser', year: 2025, color: 'Grey', status: 'ready', type: 'Car' },
  { id: 'veh-35', plate: 'TN 01 AB 0035', brand: 'Hyundai', model: 'Alcazar', year: 2021, color: 'White', status: 'ready', type: 'Car' },
  { id: 'veh-36', plate: 'TN 01 AB 0036', brand: 'Honda', model: 'WR-V', year: 2022, color: 'Silver', status: 'ready', type: 'Car' },
  { id: 'veh-37', plate: 'TN 01 AB 0037', brand: 'Kia', model: 'Carnival', year: 2023, color: 'Black', status: 'ready', type: 'Car' },
  { id: 'veh-38', plate: 'TN 01 AB 0038', brand: 'Tata', model: 'Safari', year: 2024, color: 'Dark Blue', status: 'ready', type: 'Car' },
  { id: 'veh-39', plate: 'TN 01 AB 0039', brand: 'Mahindra', model: 'Bolero', year: 2025, color: 'White', status: 'ready', type: 'Car' },
  { id: 'veh-40', plate: 'TN 01 AB 0040', brand: 'MG', model: 'Astor', year: 2021, color: 'Red', status: 'ready', type: 'Car' },
  { id: 'veh-41', plate: 'TN 01 AB 0041', brand: 'BMW', model: '3 Series', year: 2022, color: 'Black', status: 'ready', type: 'Car' },
  { id: 'veh-42', plate: 'TN 01 AB 0042', brand: 'BMW', model: '5 Series', year: 2023, color: 'White', status: 'ready', type: 'Car' },
  { id: 'veh-43', plate: 'TN 01 AB 0043', brand: 'BMW', model: 'X1', year: 2024, color: 'Blue', status: 'ready', type: 'Car' },
  { id: 'veh-44', plate: 'TN 01 AB 0044', brand: 'BMW', model: 'X5', year: 2025, color: 'Grey', status: 'ready', type: 'Car' },
  { id: 'veh-45', plate: 'TN 01 AB 0045', brand: 'Mercedes-Benz', model: 'C-Class', year: 2022, color: 'Silver', status: 'ready', type: 'Car' },
  // 46-100 placeholder vehicles
  { id: 'veh-46', plate: 'TN 01 AB 0046', brand: 'AutoBrand1', model: 'Model1', year: 2021, color: 'Red', status: 'ready', type: 'Car' },
  { id: 'veh-47', plate: 'TN 01 AB 0047', brand: 'AutoBrand2', model: 'Model2', year: 2022, color: 'Blue', status: 'ready', type: 'Car' },
  { id: 'veh-48', plate: 'TN 01 AB 0048', brand: 'AutoBrand3', model: 'Model3', year: 2023, color: 'Green', status: 'ready', type: 'Car' },
  { id: 'veh-49', plate: 'TN 01 AB 0049', brand: 'AutoBrand4', model: 'Model4', year: 2024, color: 'Yellow', status: 'ready', type: 'Car' },
  { id: 'veh-50', plate: 'TN 01 AB 0050', brand: 'AutoBrand5', model: 'Model5', year: 2025, color: 'Orange', status: 'ready', type: 'Car' },
  { id: 'veh-51', plate: 'TN 01 AB 0051', brand: 'AutoBrand6', model: 'Model6', year: 2021, color: 'Purple', status: 'ready', type: 'Car' },
  { id: 'veh-52', plate: 'TN 01 AB 0052', brand: 'AutoBrand7', model: 'Model7', year: 2022, color: 'Pink', status: 'ready', type: 'Car' },
  { id: 'veh-53', plate: 'TN 01 AB 0053', brand: 'AutoBrand8', model: 'Model8', year: 2023, color: 'Brown', status: 'ready', type: 'Car' },
  { id: 'veh-54', plate: 'TN 01 AB 0054', brand: 'AutoBrand9', model: 'Model9', year: 2024, color: 'Cyan', status: 'ready', type: 'Car' },
  { id: 'veh-55', plate: 'TN 01 AB 0055', brand: 'AutoBrand10', model: 'Model10', year: 2025, color: 'Magenta', status: 'ready', type: 'Car' },
  // Additional placeholders up to veh-100 can be added similarly.
];

export const INITIAL_MECHANICS = [
  {
    id: 'mech-1',
    name: 'Rajesh Kumar',
    phone: '+91 98450 12231',
    distance: 2.3,
    rating: 4.8,
    reviewsCount: 142,
    specialization: ['Engine', 'Battery', 'Flat Tyre'],
    latitude: 12.9716,
    longitude: 80.2209,
    isAvailable: true,
    address: 'Velachery Main Rd, Chennai',
    profileImg: '',
    vehicleDetails: 'Tow Truck - TN 22 CG 4451',
    experience: '8 years',
    serviceArea: 'South Chennai',
  },
  {
    id: 'mech-2',
    name: 'Suresh Babu',
    phone: '+91 97860 55432',
    distance: 4.1,
    rating: 4.5,
    reviewsCount: 98,
    specialization: ['Brake Issue', 'Electrical Issue', 'Overheating'],
    latitude: 13.0067,
    longitude: 80.2206,
    isAvailable: true,
    address: 'Guindy Industrial Estate, Chennai',
    profileImg: '',
    vehicleDetails: 'Mobile Service Van - TN 09 AB 7821',
    experience: '5 years',
    serviceArea: 'Central Chennai',
  },
  {
    id: 'mech-3',
    name: 'Vijay Anand',
    phone: '+91 90920 67812',
    distance: 6.7,
    rating: 4.9,
    reviewsCount: 210,
    specialization: ['Engine Malfunction', 'Fuel Problem', 'Accident Assistance'],
    latitude: 13.0475,
    longitude: 80.2090,
    isAvailable: false,
    address: 'Anna Nagar 2nd Avenue, Chennai',
    profileImg: '',
    vehicleDetails: 'Heavy Tow Rig - TN 01 BX 3300',
    experience: '12 years',
    serviceArea: 'North Chennai',
  },
  {
    id: 'mech-4',
    name: 'Karthik M',
    phone: '+91 87540 21309',
    distance: 3.5,
    rating: 4.6,
    reviewsCount: 75,
    specialization: ['Brake Issue', 'Flat Tyre', 'Battery Problem'],
    latitude: 12.9516,
    longitude: 80.1462,
    isAvailable: true,
    address: 'Tambaram East, Chennai',
    profileImg: '',
    vehicleDetails: 'Mobile Service Van - TN 22 DK 1100',
    experience: '4 years',
    serviceArea: 'Tambaram & Pallavaram',
  },
  {
    id: 'mech-5',
    name: 'Dinesh R',
    phone: '+91 93610 98712',
    distance: 8.2,
    rating: 4.3,
    reviewsCount: 54,
    specialization: ['Flat Tire', 'Dead Battery', 'Lockout / Key Lost'],
    latitude: 12.9010,
    longitude: 80.2279,
    isAvailable: true,
    address: 'Sholinganallur IT Corridor, Chennai',
    profileImg: '',
    vehicleDetails: 'Light Service Van - TN 10 CX 8870',
    experience: '3 years',
    serviceArea: 'OMR Corridor',
  },
  {
    id: 'mech-6',
    name: 'Ananth Krishnan',
    phone: '+91 94441 23456',
    distance: 3.2,
    rating: 4.7,
    reviewsCount: 110,
    specialization: ['Engine Issue', 'Battery Problem'],
    latitude: 12.9800,
    longitude: 80.2300,
    isAvailable: true,
    address: 'Adyar Flyover Rd, Chennai',
    profileImg: '',
    vehicleDetails: 'Tow Truck - TN 07 AA 1234',
    experience: '6 years',
    serviceArea: 'Adyar & Besant Nagar',
  },
  {
    id: 'mech-7',
    name: 'Balaji Srinivasan',
    phone: '+91 94442 34567',
    distance: 1.5,
    rating: 4.4,
    reviewsCount: 85,
    specialization: ['Flat Tyre', 'Brake Issue'],
    latitude: 12.9900,
    longitude: 80.2100,
    isAvailable: true,
    address: 'Velachery Bypass Rd, Chennai',
    profileImg: '',
    vehicleDetails: 'Mobile Service Van - TN 07 AB 5678',
    experience: '4 years',
    serviceArea: 'Velachery',
  },
  {
    id: 'mech-8',
    name: 'Chandrashekar Rao',
    phone: '+91 94443 45678',
    distance: 5.0,
    rating: 4.8,
    reviewsCount: 195,
    specialization: ['Engine Malfunction', 'Overheating'],
    latitude: 13.0100,
    longitude: 80.2000,
    isAvailable: true,
    address: 'T Nagar G N Chetty Rd, Chennai',
    profileImg: '',
    vehicleDetails: 'Heavy Tow Rig - TN 01 AC 9012',
    experience: '10 years',
    serviceArea: 'T Nagar & Kodambakkam',
  },
  {
    id: 'mech-9',
    name: 'Deepak Raj',
    phone: '+91 94444 56789',
    distance: 2.8,
    rating: 4.6,
    reviewsCount: 120,
    specialization: ['Fuel Problem', 'Lockout / Key Lost'],
    latitude: 13.0200,
    longitude: 80.2400,
    isAvailable: true,
    address: 'Mylapore Bazaar St, Chennai',
    profileImg: '',
    vehicleDetails: 'Light Service Van - TN 06 AD 3456',
    experience: '7 years',
    serviceArea: 'Mylapore',
  },
  {
    id: 'mech-10',
    name: 'Elango Govindan',
    phone: '+91 94445 67890',
    distance: 7.2,
    rating: 4.2,
    reviewsCount: 60,
    specialization: ['Electrical Issue', 'Other Mechanical'],
    latitude: 13.0500,
    longitude: 80.1800,
    isAvailable: true,
    address: 'Koyambedu Roundtana, Chennai',
    profileImg: '',
    vehicleDetails: 'Mobile Service Van - TN 02 AE 7890',
    experience: '3 years',
    serviceArea: 'Koyambedu',
  },
  {
    id: 'mech-11',
    name: 'Farooq Abdullah',
    phone: '+91 94446 78901',
    distance: 6.1,
    rating: 4.9,
    reviewsCount: 220,
    specialization: ['Engine Issue', 'Accident Assistance'],
    latitude: 13.0800,
    longitude: 80.2200,
    isAvailable: true,
    address: 'Egmore High Rd, Chennai',
    profileImg: '',
    vehicleDetails: 'Heavy Tow Rig - TN 01 AF 1234',
    experience: '15 years',
    serviceArea: 'Egmore & Central',
  },
  {
    id: 'mech-12',
    name: 'Ganesan Murthy',
    phone: '+91 94447 89012',
    distance: 4.5,
    rating: 4.5,
    reviewsCount: 102,
    specialization: ['Dead Battery', 'Flat Tire'],
    latitude: 13.0300,
    longitude: 80.1700,
    isAvailable: true,
    address: 'Vadapalani Jn, Chennai',
    profileImg: '',
    vehicleDetails: 'Tow Truck - TN 09 AG 5678',
    experience: '8 years',
    serviceArea: 'Vadapalani',
  },
  {
    id: 'mech-13',
    name: 'Harish Ramakrishnan',
    phone: '+91 94448 90123',
    distance: 3.9,
    rating: 4.7,
    reviewsCount: 140,
    specialization: ['Brake Issue', 'Overheating'],
    latitude: 12.9600,
    longitude: 80.1800,
    isAvailable: true,
    address: 'Chromepet GST Rd, Chennai',
    profileImg: '',
    vehicleDetails: 'Mobile Service Van - TN 22 AH 9012',
    experience: '6 years',
    serviceArea: 'Chromepet',
  },
  {
    id: 'mech-14',
    name: 'Imran Khan',
    phone: '+91 94449 01234',
    distance: 8.5,
    rating: 4.3,
    reviewsCount: 78,
    specialization: ['Fuel Starvation', 'Flat Tyre'],
    latitude: 13.0900,
    longitude: 80.2700,
    isAvailable: true,
    address: 'Royapuram Beach Rd, Chennai',
    profileImg: '',
    vehicleDetails: 'Light Service Van - TN 03 AJ 3456',
    experience: '5 years',
    serviceArea: 'Royapuram',
  },
  {
    id: 'mech-15',
    name: 'Jayakumar Sundaram',
    phone: '+91 94440 12345',
    distance: 5.5,
    rating: 4.6,
    reviewsCount: 115,
    specialization: ['Engine Malfunction', 'Dead Battery'],
    latitude: 13.0400,
    longitude: 80.2500,
    isAvailable: true,
    address: 'Triplicane High Rd, Chennai',
    profileImg: '',
    vehicleDetails: 'Tow Truck - TN 01 AK 7890',
    experience: '9 years',
    serviceArea: 'Triplicane & Marina',
  },
  {
    id: 'mech-16',
    name: 'Kavin Selvam',
    phone: '+91 94431 23456',
    distance: 2.1,
    rating: 4.8,
    reviewsCount: 160,
    specialization: ['Battery Problem', 'Break Fail'],
    latitude: 12.9950,
    longitude: 80.2250,
    isAvailable: true,
    address: 'Guindy Ekkattuthangal, Chennai',
    profileImg: '',
    vehicleDetails: 'Mobile Service Van - TN 22 AL 1234',
    experience: '7 years',
    serviceArea: 'Guindy & Ekkattuthangal',
  },
  {
    id: 'mech-17',
    name: 'Loganathan Pillai',
    phone: '+91 94432 34567',
    distance: 9.0,
    rating: 4.4,
    reviewsCount: 92,
    specialization: ['Overheating', 'Accident Assistance'],
    latitude: 13.0600,
    longitude: 80.1200,
    isAvailable: true,
    address: 'Poonamallee Bypass, Chennai',
    profileImg: '',
    vehicleDetails: 'Heavy Tow Rig - TN 12 AM 5678',
    experience: '11 years',
    serviceArea: 'Poonamallee',
  },
  {
    id: 'mech-18',
    name: 'Mani Kandan',
    phone: '+91 94433 45678',
    distance: 3.4,
    rating: 4.7,
    reviewsCount: 135,
    specialization: ['Flat Tyre', 'Fuel Problem'],
    latitude: 13.0250,
    longitude: 80.2150,
    isAvailable: true,
    address: 'Ashok Nagar 11th Ave, Chennai',
    profileImg: '',
    vehicleDetails: 'Light Service Van - TN 09 AN 9012',
    experience: '8 years',
    serviceArea: 'Ashok Nagar',
  },
  {
    id: 'mech-19',
    name: 'Naveen Prasad',
    phone: '+91 94434 56789',
    distance: 6.8,
    rating: 4.5,
    reviewsCount: 105,
    specialization: ['Electrical Issue', 'Engine Issue'],
    latitude: 13.0700,
    longitude: 80.2000,
    isAvailable: true,
    address: 'Kilpauk Garden Rd, Chennai',
    profileImg: '',
    vehicleDetails: 'Mobile Service Van - TN 01 AP 3456',
    experience: '5 years',
    serviceArea: 'Kilpauk',
  },
  {
    id: 'mech-20',
    name: 'Parthiban R',
    phone: '+91 94435 67890',
    distance: 4.2,
    rating: 4.6,
    reviewsCount: 110,
    specialization: ['Battery Problem', 'Lockout / Key Lost'],
    latitude: 13.0350,
    longitude: 80.2350,
    isAvailable: true,
    address: 'Alwarpet TTK Rd, Chennai',
    profileImg: '',
    vehicleDetails: 'Light Service Van - TN 07 AQ 7890',
    experience: '6 years',
    serviceArea: 'Alwarpet',
  },
  {
    id: 'mech-21',
    name: 'Raghu Raman',
    phone: '+91 94436 78901',
    distance: 5.9,
    rating: 4.9,
    reviewsCount: 230,
    specialization: ['Brake Issue', 'Engine Malfunction'],
    latitude: 13.0450,
    longitude: 80.1950,
    isAvailable: true,
    address: 'Saligramam Arcot Rd, Chennai',
    profileImg: '',
    vehicleDetails: 'Tow Truck - TN 09 AR 1234',
    experience: '12 years',
    serviceArea: 'Saligramam',
  },
  {
    id: 'mech-22',
    name: 'Saravanan P',
    phone: '+91 94437 89012',
    distance: 2.7,
    rating: 4.7,
    reviewsCount: 155,
    specialization: ['Flat Tire', 'Dead Battery'],
    latitude: 12.9650,
    longitude: 80.2450,
    isAvailable: true,
    address: 'Perungudi OMR, Chennai',
    profileImg: '',
    vehicleDetails: 'Mobile Service Van - TN 07 AS 5678',
    experience: '7 years',
    serviceArea: 'Perungudi & OMR',
  },
  {
    id: 'mech-23',
    name: 'Thirumal V',
    phone: '+91 94438 90123',
    distance: 8.0,
    rating: 4.3,
    reviewsCount: 88,
    specialization: ['Overheating', 'Fuel Starvation'],
    latitude: 13.1200,
    longitude: 80.2100,
    isAvailable: true,
    address: 'Madhavaram Milk Colony, Chennai',
    profileImg: '',
    vehicleDetails: 'Heavy Tow Rig - TN 05 AT 9012',
    experience: '10 years',
    serviceArea: 'Madhavaram',
  },
  {
    id: 'mech-24',
    name: 'Udayakumar S',
    phone: '+91 94439 01234',
    distance: 4.8,
    rating: 4.6,
    reviewsCount: 125,
    specialization: ['Engine Issue', 'Electrical Issue'],
    latitude: 13.0150,
    longitude: 80.1850,
    isAvailable: true,
    address: 'Ramapuram Mount Poonamallee Rd, Chennai',
    profileImg: '',
    vehicleDetails: 'Mobile Service Van - TN 10 AU 3456',
    experience: '8 years',
    serviceArea: 'Ramapuram',
  },
  {
    id: 'mech-25',
    name: 'Vigneshwaran K',
    phone: '+91 94430 12345',
    distance: 3.1,
    rating: 4.8,
    reviewsCount: 175,
    specialization: ['Flat Tyre', 'Battery Problem'],
    latitude: 12.9850,
    longitude: 80.2150,
    isAvailable: true,
    address: 'Velachery Taramani Link Rd, Chennai',
    profileImg: '',
    vehicleDetails: 'Tow Truck - TN 22 AV 7890',
    experience: '9 years',
    serviceArea: 'Velachery & Taramani',
  },
];

// ─── Breakdown Reports (history) ─────────────────────────────────────────
export const INITIAL_REPORTS: import('./types').BreakdownReport[] = [
  {
    id: 'rpt-1',
    vehicleId: 'veh-1',
    vehicleName: 'Toyota Camry (TN 01 AB 0001)',
    breakdownType: 'Flat Tyre',
    description: 'Front-left tyre burst on ECR near Thiruvanmiyur junction.',
    severity: 'Medium',
    status: 'completed',
    locationName: 'Thiruvanmiyur, Chennai',
    latitude: 12.9855,
    longitude: 80.2683,
    mechanicId: 'mech-1',
    mechanicName: 'Rajesh Kumar',
    requestedAt: '2026-06-10T09:30:00',
    updatedAt: '2026-06-10T10:45:00',
    totalCost: 850,
    rating: 5,
    feedback: 'Arrived quickly and fixed the tyre efficiently!',
    paymentStatus: 'paid',
    paymentMethod: 'upi',
  },
  {
    id: 'rpt-2',
    vehicleId: 'veh-3',
    vehicleName: 'Hyundai Creta (TN 01 AB 0003)',
    breakdownType: 'Battery Problem',
    description: 'Battery completely dead. Vehicle stalled near Adyar signal.',
    severity: 'High',
    status: 'completed',
    locationName: 'Adyar, Chennai',
    latitude: 13.0012,
    longitude: 80.2565,
    mechanicId: 'mech-2',
    mechanicName: 'Suresh Babu',
    requestedAt: '2026-06-08T14:20:00',
    updatedAt: '2026-06-08T15:30:00',
    totalCost: 2200,
    rating: 4,
    feedback: 'Good service, replaced battery on spot.',
    paymentStatus: 'paid',
    paymentMethod: 'card',
  },
  {
    id: 'rpt-3',
    vehicleId: 'veh-7',
    vehicleName: 'Mahindra XUV700 (TN 01 AB 0007)',
    breakdownType: 'Engine Issue',
    description: 'Engine overheating warning on dashboard. Pulled over near Porur bridge.',
    severity: 'Critical SOS',
    status: 'completed',
    locationName: 'Porur, Chennai',
    latitude: 13.0382,
    longitude: 80.1567,
    mechanicId: 'mech-3',
    mechanicName: 'Vijay Anand',
    requestedAt: '2026-06-05T18:50:00',
    updatedAt: '2026-06-05T20:10:00',
    totalCost: 4500,
    rating: 5,
    feedback: 'Handled critical situation calmly. Towed to nearby service centre.',
    paymentStatus: 'paid',
    paymentMethod: 'card',
  },
];

// ─── Notifications ───────────────────────────────────────────────────────
export const INITIAL_NOTIFICATIONS: import('./types').NotificationAlert[] = [
  {
    id: 'notif-1',
    title: 'Welcome to RoadAssist OS',
    message: 'Your roadside assistance platform is ready. Explore features and simulate breakdowns.',
    type: 'info',
    timestamp: '2026-06-13T08:00:00',
    read: false,
  },
  {
    id: 'notif-2',
    title: 'Service Completed',
    message: 'Your last service request (Flat Tyre at Thiruvanmiyur) has been marked completed.',
    type: 'success',
    timestamp: '2026-06-10T10:45:00',
    read: true,
  },
  {
    id: 'notif-3',
    title: 'SOS Feature Enabled',
    message: 'Critical SOS one-tap emergency dispatch is now active for your account.',
    type: 'warning',
    timestamp: '2026-06-09T12:00:00',
    read: false,
  },
  {
    id: 'notif-4',
    title: 'Payment Confirmed',
    message: 'Payment of ₹2,200 via card for Battery Replacement at Adyar confirmed.',
    type: 'success',
    timestamp: '2026-06-08T15:35:00',
    read: true,
  },
];

// ─── System Metrics (Admin Dashboard) ────────────────────────────────────
export const SYSTEM_METRICS = {
  totalRequests: 1247,
  activeNow: 3,
  completedToday: 18,
  avgResponseTime: '8.2 min',
  averageResponseMs: 8.2,
  totalMechanics: 45,
  availableMechanics: 32,
  activeMechanics: 32,
  totalUsers: 3860,
  revenue: 284500,
  cancelRate: 4.2,
  satisfaction: 4.7,
  towedAggregate: 1159,
  regionalHotspots: [
    { name: 'Silk Board Junction', count: 87, rate: 'High' as const },
    { name: 'OMR – Sholinganallur', count: 64, rate: 'High' as const },
    { name: 'Guindy Industrial Belt', count: 45, rate: 'Medium' as const },
    { name: 'Tambaram – Chengalpattu NH', count: 38, rate: 'Medium' as const },
    { name: 'Anna Nagar Flyover', count: 22, rate: 'Low' as const },
    { name: 'Porur – Kundrathur Rd', count: 19, rate: 'Low' as const },
  ],
};

// ─── FAQs ────────────────────────────────────────────────────────────────
export const FAQS: import('./types').FAQItem[] = [
  {
    id: 'faq-1',
    question: 'How do I request roadside assistance?',
    answer: 'Go to the Customer Dashboard, click "New Breakdown Request", fill in your vehicle and breakdown details, and submit. A nearby mechanic will be dispatched automatically.',
    category: 'assistance',
  },
  {
    id: 'faq-2',
    question: 'What payment methods are accepted?',
    answer: 'We accept UPI, credit/debit cards, Apple Pay, and cash payments. You can choose your preferred method after service completion.',
    category: 'payment',
  },
  {
    id: 'faq-3',
    question: 'How do I track my mechanic in real-time?',
    answer: 'Once a mechanic accepts your request, you can see their live location on the map in your dashboard with estimated arrival time.',
    category: 'assistance',
  },
  {
    id: 'faq-4',
    question: 'How do I register as a mechanic?',
    answer: 'Click "Need roadside credentials? Build Account" on the login page, select the Mechanic role, and provide your certification and tow truck details.',
    category: 'mechanic',
  },
  {
    id: 'faq-5',
    question: 'Can I cancel a service request?',
    answer: 'Yes, you can cancel before a mechanic arrives. Go to your active request and click "Cancel Request". Note that repeated cancellations may affect your account standing.',
    category: 'assistance',
  },
  {
    id: 'faq-6',
    question: 'How do I reset my password?',
    answer: 'Click "Forgot Key?" on the login page and follow the instructions sent to your registered email address.',
    category: 'accounts',
  },
];
